"""empty message

Revision ID: 11e3923f17cb
Revises: d8d369a5819c
Create Date: 2021-04-18 12:56:04.847054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e3923f17cb'
down_revision = 'd8d369a5819c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottles', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bottles', 'posted')
    # ### end Alembic commands ###
