"""empty message

Revision ID: afa4b48eab9c
Revises: 11e3923f17cb
Create Date: 2021-04-19 13:56:57.961706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa4b48eab9c'
down_revision = '11e3923f17cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottles', sa.Column('owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bottles', 'owner')
    # ### end Alembic commands ###
