"""empty message

Revision ID: b1442a4a6de0
Revises: afa4b48eab9c
Create Date: 2021-04-26 17:21:23.706065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1442a4a6de0'
down_revision = 'afa4b48eab9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottles', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bottles', 'notes')
    # ### end Alembic commands ###
